# mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learn_spring_data?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: password
    #driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    initialization-mode: never

  # jpa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    open-in-view: false
